spring:
  application:
    name: moniter-center
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
#监控中心
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
